package commons;

public class SuccessCodes {
	// example
	public static final String CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
	public static final String DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
	public static final String UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS";
	
	public static final String CREATE_ACCOUNT_SUCCESS = "CREATE_ACCOUNT_SUCCESS";
	public static final String DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
	public static final String UPDATE_ACCOUNT_SUCCESS = "UPDATE_ACCOUNT_SUCCESS";
	public static final String UPDATE_PAGE_SUCCESS = "UPDATE_PAGE_SUCCESS";
	public static final String CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
	public static final String DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";
	public static final String APPROVE_POST_SUCCESS = "APPROVE_POST_SUCCESS";
	public static final String CREATE_COURSE_SUCESS = "CREATE_COURSE_SUCESS";
	public static final String UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS";
	public static final String DELETE_COURSE_SUCCESS = "DELETE_COURSE_SUCCESS";
	public static final String CREATE_CERTIFICATION_SUCCESS = "CREATE_CERTIFICATION_SUCCESS";
	public static final String UPDATE_CERTIFICATION_SUCCESS = "UPDATE_CERTIFICATION_SUCCESS";
	public static final String CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS";
	public static final String DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";
	public static final String UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";
	public static final String UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
	public static final String CHANGE_IMAGE_SUCCESS = "CHANGE_IMAGE_SUCCESS";
	public static final String CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
	public static final String CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
	public static final String UPDATE_SCORE_SUCCESS = "UPDATE_SCORE_SUCCESS";
	public static final String APPROVE_CERTIFICATE_SUCCESS = "APPROVE_CERTIFICATE_SUCCESS";
}
